name: Deploy Cocoapods

on:
  push:
    branches: 
      - develop
    paths:
      - 'ActionSheetPicker-3.0.podspec' 

jobs:

  deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - run: gem install cocoapods
    - env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings

        
